- name: install nginx
  hosts: webservers
  become: yes
  remote_user: root
  tasks:
  - name: Installs Nginx web server
    apt: pkg=nginx state=latest update_cache=true
    notify:
      - start nginx
  