# - name: install nginx
#   hosts: localhost
#   connection: local
#   become: ec2-user
#   remote_user: ec2-user
#   tasks:
#   - name: Installs Nginx web server
#     shell: | 
#       cd ~/cdn
#       npm run build

- name: clone git repo and build it
  hosts: webservers
  roles:
    - role: '../gitcloneRole.yaml'
  become: yes
  remote_user: ec2-user
  tasks:
  - name: Upgrade all packages
    ansible.builtin.yum:
      name: '*'
      state: latest
  - name: Install git
    ansible.builtin.yum:
      name: git
      state: present
  # - name: Install dependencies
  #   shell: |
  #    sudo yum update -y
  #    sudo yum install git -y 
  #    git version
     
  # - name: clone git repo
  #   git:
  #      repo: https://github.com/AliHaider5674/cdn.git
  #      dest: /home/ec2-user/repo/
  #      clone: yes
  #      force: yes
  #      update: yes
  - name: make build
    shell: | 
      cd /home/ec2-user/repo/
      npm i
      npm run build
      npm install -g serve
  # - name: "Copy build  file from master to target"
  #   copy: src=../cdn/build/  dest=/usr/share/nginx/html
  # sudo amazon-linux-extras install nginx1
