# - name: install nginx
#   hosts: localhost
#   connection: local
#   become: ec2-user
#   remote_user: ec2-user
#   tasks:
#   - name: Installs Nginx web server
#     shell: | 
#       cd ~/cdn
#       npm run build
- name: clone git repo and build it
  hosts: webservers
  become: yes
  remote_user: ec2-user
  tasks:
  - name: clone git repo
    shell: |
      cd ~/.ssh/
      git clone https://github.com/AliHaider5674/cdn.git
  # - name: "Copy build  file from master to target"
  #   copy: src=../cdn/build/  dest=/usr/share/nginx/html
  # sudo amazon-linux-extras install nginx1
