# - name: install nginx
#   hosts: localhost
#   connection: local
#   become: ec2-user
#   remote_user: ec2-user
#   tasks:
#   - name: Installs Nginx web server
#     shell: | 
#       cd ~/cdn
#       npm run build

- name: clone git repo and build it
  hosts: webservers
  become_users: ec2-user
  remote_user: ec2-user
  tasks:
  - name: Install dependencies
    shell: |
     sudo yum update -y
     sudo yum install git -y
     git version
     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
     . ~/.nvm/nvm.sh
     nvm install 15.0.0
     node -e "console.log('Running Node.js ' + process.version)"
  - name: clone git repo
    git:
       repo: https://github.com/AliHaider5674/cdn.git
       dest: /home/ec2-user/repo/
       clone: yes
       update: yes
  - name: make build
    shell: | 
      cd ~/repo/
      npm install
      npm start
      npm run build
  # - name: "Copy build  file from master to target"
  #   copy: src=../cdn/build/  dest=/usr/share/nginx/html
  # sudo amazon-linux-extras install nginx1
