# - name: install nginx
#   hosts: localhost
#   connection: local
#   become: ec2-user
#   remote_user: ec2-user
#   tasks:
#   - name: Installs Nginx web server
#     shell: | 
#       cd ~/cdn
#       npm run build
- name: clone git repo and build it
  hosts: webservers
  become: yes
  remote_user: ec2-user
  tasks:
  - name: clone git repo
    git:
       repo: https://github.com/AliHaider5674/cdn.git
       dest: /home/ec2-user/repo/
       clone: yes
       update: yes
  # - name: "Copy build  file from master to target"
  #   copy: src=../cdn/build/  dest=/usr/share/nginx/html
  # sudo amazon-linux-extras install nginx1
