- name: update web servers
  hosts: webservers
  become: yes
  remote_user: root
  vars:
    ssh_key_filename: id_rsa_myproject
  tasks:
  - name: "Create group"
    group:
      name: "admin_group"
      state: present
  - name: "Create user accounts"
    user:
      name: "ali"
      groups: "admin_group"
  - name: "Allow admin users to sudo without a password"
    lineinfile:
      dest: "/etc/sudoers" # path: in version 2.3
      state: "present"
      regexp: "^%admin"
      line: "%admin ALL=(ALL) NOPASSWD: ALL"
  - name: "SSH KeyGen command"
    tags: run
    shell: > 
      ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
        creates="~/.ssh/id_rsa"
  - name: "Fetch the keyfile from one server to another"
    tags: run 
    fetch: 
      src: "~/.ssh/id_rsa.pub"
      dest: "buffer/id_rsa.pub"
      flat: yes
  - name: "Copy the key add to authorized_keys using Ansible module"
    tags: run
    authorized_key:
      user: ali
      state: present
      key: "{{ lookup('file','buffer/id_rsa.pub')}}"
  # - name: "copy public SSH key"
  #   authorized_key:
  #     user: ali
  #     state: present
  #     manage_dir: yes
  #     key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    
      
