- name: update web servers
  hosts: webservers
  become: true
  remote_user: root
  vars:
    ssh_key_filename: id_rsa_myproject
  tasks:
  - name: "Create group"
    group:
      name: "admin_group"
      state: present
  - name: "Create user accounts"
    user:
      name: "ali"
      groups: "admin_group"
  - name: "Allow admin users to sudo without a password"
    lineinfile:
      dest: "/etc/sudoers" # path: in version 2.3
      state: "present"
      regexp: "^%admin"
      line: "%admin ALL=(ALL) NOPASSWD: ALL"
  - name: "generate SSH key"
    openssh_keypair:
      path: "~/.ssh/{{ssh_key_filename}}"
      type: rsa
      size: 4096
      state: present
      force: no
      
