- name: Install IKEv2 VPN server for macOS / iOS
  # Specify hosts here
  hosts: webservers 
  become: yes
  tasks:
    - name: Install packages
      apt: 
        name: "{{ item.package_name }}"
        state: present
        update_cache: yes
      loop:
        - { package_name: strongswan-pki }
        - { package_name: libcharon-extra-plugins }
        - { package_name: libcharon-extauth-plugins }
        - { package_name: libstrongswan-extra-plugins }
    - name: Creates directory
      file:
        path: ~/pki/{cacerts,certs,private}
        state: directory
        mode: '700'
  
    - name: Generating a Certificate for the VPN Server
      shell: |
        pki --gen --type rsa --size 4096 --outform pem > ~/pki/private/ca-key.pem
        pki --self --ca --lifetime 3650 --in ~/pki/private/ca-key.pem \
          --type rsa --dn "CN=VPN root CA" --outform pem > ~/pki/cacerts/ca-cert.pem
        pki --gen --type rsa --size 4096 --outform pem > ~/pki/private/server-key.pem
        pki --pub --in ~/pki/private/server-key.pem --type rsa \
        | pki --issue --lifetime 1825 \
        --cacert ~/pki/cacerts/ca-cert.pem \
        --cakey ~/pki/private/ca-key.pem \
        --dn "CN=52.36.43.24" --san 52.36.43.24 \
        --flag serverAuth --flag ikeIntermediate --outform pem \
        >  ~/pki/certs/server-cert.pem
        
    - name: Configuring StrongSwan
      shell: |
        cp -r ~/pki/* /etc/ipsec.d/
    - name: Ansible blockinfile insertafter and insertbefore
      blockinfile:
        dest: /etc/ipsec.conf
        block: |
          config setup
              charondebug="ike 1, knl 1, cfg 0"
              uniqueids=no
          conn ikev2-vpn
              auto=add
              compress=no
              type=tunnel
              keyexchange=ikev2
              fragmentation=yes
              forceencaps=yes
              dpdaction=clear
              dpddelay=300s
              rekey=no
              left=%any
              leftid=@server_domain_or_IP
              leftcert=server-cert.pem
              leftsendcert=always
              leftsubnet=0.0.0.0/0
              right=%any
              rightid=%any
              rightauth=eap-mschapv2
              rightsourceip=10.10.10.0/24
              rightdns=8.8.8.8,8.8.4.4
              rightsendcert=never
              eap_identity=%identity
              ike=chacha20poly1305-sha512-curve25519-prfsha512,aes256gcm16-sha384-prfsha384-ecp384,aes256-sha1-modp1024,aes128-sha1-modp1024,3des-sha1-modp1024!
              esp=chacha20poly1305-sha512,aes256gcm16-ecp384,aes256-sha256,aes256-sha1,3des-sha1!
        insertbefore: BOF